In [16]:
import pandas as pd 
import matplotlib.pyplot as plt
import numpy as np

In [ ]:
csv = pd.read_csv("../social-comment-map-main/YoutubeCommentsDataSet.csv")

csv.head()

                                             Comment Sentiment
0  lets not forget that apple pay in 2014 require...   neutral
1  here in nz 50 of retailers don’t even have con...  negative
2  i will forever acknowledge this channel with t...  positive
3  whenever i go to a place that doesn’t take app...  negative
4  apple pay is so convenient secure and easy to ...  positive

In [18]:
csv["ai_kindness"] = ""
csv["ai_seroiusnes"] = ""
csv["user_nickname"] = ""
csv["nickname_score"] = ""
csv.head()

,Comment,Sentiment,ai_kindness,ai_seroiusnes,user_nickname,nickname_score
0,lets not forget that apple pay in 2014 require...,neutral,,,,
1,here in nz 50 of retailers don’t even have con...,negative,,,,
2,i will forever acknowledge this channel with t...,positive,,,,
3,whenever i go to a place that doesn’t take app...,negative,,,,
4,apple pay is so convenient secure and easy to ...,positive,,,,

In [19]:
import ollama

In [43]:
import time 

golabal_comment_count = 0

single_name_prompt = """
Generate exactly ONE random username that could appear on social media. Those could be nicknames, real life names, names of famous personalities or anyting else. dont forget to use real names sometimes. Return the nick name alone , without any explanation or addition text"""




def random_ai_name():
    response = ollama.generate(model="llama3.1:8b", prompt= single_name_prompt)
    return response["response"]


def nickname_score():
    response = ollama.generate(model="llama3.1:8b", prompt= ai_nick_score_prompt)
    return response["response"]

def kindness_score():
    response = ollama.generate(model="llama3.1:8b", prompt= kindness_prompt)
    return response["response"]

def seriousness_score():
    response = ollama.generate(model="llama3.1:8b", prompt= seriousness_prompt)
    return response["response"]



ai_nick_score_prompt = f""" Analyze the username "{random_ai_name()}" and estimate from 0.00 to 1.00 how likely it is to be a real person's legal name. Dont forget, you can score only between 0.00 and 1.00.  You ONLY give the score, without any additional text. Example: "0.4" or "0.85".
"""
control = random_ai_name()
print("Control Name: ", control)
kindness_prompt = f"""Analyze this comment for harmful content: "{csv.iloc[golabal_comment_count][0]}" SCORING GUIDE: 0.0:, 1.0: Direct threats or extreme hate speech. Dont forget, you can score only between 0.0 and 1.0. You ONLY give the score, without any additional text. Example: "0.4" or "0.85"
"""

seriousness_prompt = f""" Analyze the seriousness and intent of this comment: "{csv.iloc[golabal_comment_count][0]}" SCORING GUIDE: 0.0,  1.0: Extremely serious, threatening, or potentially damaging Consider these factors: - Use of emojis, jokes, or sarcasm indicators - Formal vs. informal language - Emotional weight and topic sensitivity - Clear intent to harm vs. inform vs. entertain Dont forget, you can score only between 0.0 and 1.0.  You ONLY give the score, without any additional text. Example: "0.4" or "0.85"""

Control Name:  XxStardust95xX

/var/folders/ls/vwzpb4gs5p11s0862ytdycch0000gn/T/ipykernel_28325/3797165465.py:34: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  kindness_prompt = f"""Analyze this comment for harmful content: "{csv.iloc[golabal_comment_count][0]}" SCORING GUIDE: 0.0:, 1.0: Direct threats or extreme hate speech. Dont forget, you can score only between 0.0 and 1.0. You ONLY give the score, without any additional text. Example: "0.4" or "0.85"
/var/folders/ls/vwzpb4gs5p11s0862ytdycch0000gn/T/ipykernel_28325/3797165465.py:37: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  seriousness_prompt = f""" Analyze the seriousness and intent of this comment: "{csv.iloc[golabal_comment_count][0]}" SCORING GUIDE: 0.0,  1.0: Extremely serious, threatening, or potentially damaging Consider these factors: - Use of emojis, jokes, or sarcasm indicators - Formal vs. informal language - Emotional weight and topic sensitivity - Clear intent to harm vs. inform vs. entertain Dont forget, you can score only between 0.0 and 1.0.  You ONLY give the score, without any additional text. Example: "0.4" or "0.85"""

In [9]:

for i in range(10):
    csv.iloc[i, 4] = f"{random_ai_name()}"
    csv.iloc[i, 5] = f"{nickname_score()}"
    csv.iloc[i, 2] = f"{kindness_score()}"
    csv.iloc[i, 3] = f"{seriousness_score()}"
    golabal_comment_count += 1

csv.head()

,Comment,Sentiment,ai_kindness,ai_seroiusnes,user_nickname,nickname_score
0,lets not forget that apple pay in 2014 require...,neutral,0.0,0.35,MoonlightMaeve,0.72
1,here in nz 50 of retailers don’t even have con...,negative,0.05,0.25,LiamMcFlyer123,0.45
2,i will forever acknowledge this channel with t...,positive,0.00,0.2,LilUziVeri,0.02
3,whenever i go to a place that doesn’t take app...,negative,0.05,0.2,MysticKairos,0.82
4,apple pay is so convenient secure and easy to ...,positive,0.00,0.15,PixieLuna,0.58

In [15]:

for i in range(0, 10):
    csv.iloc[i, 4] = f"{random_ai_name()}"
    csv.iloc[i, 5] = f"{nickname_score()}"
    csv.iloc[i, 2] = f"{kindness_score()}"
    csv.iloc[i, 3] = f"{seriousness_score()}"
    golabal_comment_count += 1

csv.head()

,Comment,Sentiment,ai_kindness,ai_seroiusnes,user_nickname,nickname_score
0,lets not forget that apple pay in 2014 require...,neutral,0.0,0.15,AuroraSpark,0.62
1,here in nz 50 of retailers don’t even have con...,negative,0.25,0.15,PixieLynx23,0.62
2,i will forever acknowledge this channel with t...,positive,0.0,0.2,XoxoSparkles90,0.72
3,whenever i go to a place that doesn’t take app...,negative,0.0,0.05,RavenKing95,0.25
4,apple pay is so convenient secure and easy to ...,positive,0.0,0.15,@XxLilithRoseXx,0.75

In [25]:
csv.iloc[0][2]

/var/folders/ls/vwzpb4gs5p11s0862ytdycch0000gn/T/ipykernel_28325/2463240567.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  csv.iloc[0][2]

'0.0'

In [28]:
type(csv.iloc[0][2])

/var/folders/ls/vwzpb4gs5p11s0862ytdycch0000gn/T/ipykernel_28325/1194475894.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  type(csv.iloc[0][2])

float

In [ ]:
fig = plt.figure(figsize= (7,6))
ax = fig.add_subplot(projection='3d')

counter = 0
while True:
    csv.iloc[counter, 4] = f"{random_ai_name()}"
    csv.iloc[counter, 5] = f"{nickname_score()}"
    csv.iloc[counter, 2] = f"{kindness_score()}"
    csv.iloc[counter, 3] = f"{seriousness_score()}"
    golabal_comment_count += 1


    csv.loc[counter, "ai_kindness"] = float(csv.loc[counter, "ai_kindness"])#kindness
    csv.loc[counter, "ai_seroiusnes"] = float(csv.loc[counter, "ai_seroiusnes"])#seroiusness
    csv.loc[counter, "nickname_score"] = float(csv.loc[counter, "nickname_score"])#Nick_score
    counter += 1
    if counter % 100 == 0:
        for s in range(counter):
            for m  in ('o'):
                x = csv.iloc[s][2] # Kindess
                y = csv.iloc[s][3]   #Seroiusness
                z = csv.iloc[s][5]   #Nickname_score
                ax.scatter(x,y,z, marker=m, alpha= 0.8, s =7)

        ax.set_xlabel('Rudeness')
        ax.set_ylabel('Seriousness')
        ax.set_zlabel('Name_Score',labelpad=1)


        ax.set_xlim(0,1)
        ax.set_ylim(0,1)
        ax.set_zlim(0,1)
        plt.show()


    
    if counter == 100:
        print("test print 2")
        break